// All the text shown in the UI lives here so we don't hardcode strings everywhere.
// Usage: const { t } = useI18n(); then t("play") gives back "Play".
// One language only, so it's just a dictionary and a lookup.

const strings = {
  app_name: "AlgoRythm",
  brand: "Where code \nbecomes music",
  tagline:
    "Write text. Hear music. A composable, browser-based sequencer. Here music is generated by logic!",
  scroll_cue: "Scroll to compose",

  nav_composer: "Composer",
  nav_library: "Library",
  nav_syntax: "Syntax Guide",

  bpm: "BPM",
  play: "Play",
  stop: "Stop",
  source: "Pattern source",
  grid: "Sequencer grid",
  examples: "Example patterns",
  tracks: "tracks",
  rest_hint: "Use - for a rest.",
  mixer: "Mixer",
  mute: "Mute",
  solo: "Solo",
  master: "Master",
  visualizer: "Visualizer",
  errors: "Pattern errors",

  how_title: "How it works",
  how_body:
    "The Parser splits each line on ':' into a track kind and tokens. Drum tokens become Note objects bound to a percussion Instrument subclass. Melody tokens like C4 or F#5 are converted to frequencies via 440·2^((midi−69)/12). The Sequencer schedules notes ~100ms ahead on the Web Audio clock, keeping timing sample-accurate.",

  lib_title: "Instrument Library",
  lib_sub:
    "Every command you can write in a pattern. Click any card to copy its sample line.",
  category_drum: "Percussion",
  category_pitched: "Pitched",
  preview: "Preview sound",
  copy: "Copy",
  copied: "Copied",
  open_composer: "Open in composer",

  syntax_title: "Syntax Guide",
  syntax_sub: "Learn the small language that powers every track.",
} as const;

export type TextKey = keyof typeof strings;

export function useI18n() {
  const t = (key: TextKey) => strings[key];
  return { t };
}
