// All the text shown in the UI lives here so we don't hardcode strings everywhere.
// Usage: const { t } = useI18n(); then t("play") gives back "Play".
// One language only, so it's just a dictionary and a lookup.

const strings = {
  app_name: "AlgoRythm",
  brand: "Where code \nbecomes music",
  tagline:
    "Write text. Hear music. A composable, browser-based sequencer. Here music is generated by logic!",
  scroll_cue: "Scroll to compose",

  nav_composer: "Composer",
  nav_library: "Library",
  nav_syntax: "Syntax Guide",
  nav_explore: "Explore",
  nav_feed: "Feed",

  bpm: "BPM",
  play: "Play",
  stop: "Stop",
  source: "Pattern source",
  grid: "Sequencer grid",
  examples: "Example patterns",
  tracks: "tracks",
  rest_hint: "Use - for a rest.",
  mixer: "Mixer",
  mute: "Mute",
  solo: "Solo",
  master: "Master",
  visualizer: "Visualizer",
  errors: "Pattern errors",

  // Auth
  login: "Log in",
  signup: "Sign up",
  logout: "Log out",
  username: "Username",
  login_id: "Username or email",
  email: "Email",
  password: "Password",
  close: "Close",

  // Save / load compositions
  my_compositions: "My compositions",
  composition_title: "Composition title",
  save: "Save",
  load: "Load",
  delete: "Delete",
  login_to_save: "Log in to save your compositions.",
  title_required: "Please enter a title.",

  // Publish / explore / profiles
  publish: "Publish",
  unpublish: "Unpublish",
  copy_link: "Copy link",
  link_copied: "Link copied",
  by: "by",
  explore_title: "Explore",
  explore_sub: "Public compositions from the community.",
  empty_explore: "No public compositions yet — publish one to get started.",
  not_found: "This isn't available.",
  joined: "Joined",
  published_works: "Published compositions",
  no_published: "No published compositions yet.",

  // Follows + feed
  follow: "Follow",
  unfollow: "Unfollow",
  followers: "Followers",
  following: "Following",
  feed_title: "Following",
  feed_sub: "New public work from people you follow.",
  empty_feed: "Nothing here yet — follow someone to see their work.",
  login_to_feed: "Log in to see your following feed.",

  how_title: "How it works",
  how_body:
    "The Parser splits each line on ':' into a track kind and tokens. Drum tokens become Note objects bound to a percussion Instrument subclass. Melody tokens like C4 or F#5 are converted to frequencies via 440·2^((midi−69)/12). The Sequencer schedules notes ~100ms ahead on the Web Audio clock, keeping timing sample-accurate.",

  lib_title: "Instrument Library",
  lib_sub: "Every command you can write in a pattern. Click any card to copy its sample line.",
  category_drum: "Percussion",
  category_pitched: "Pitched",
  preview: "Preview sound",
  copy: "Copy",
  copied: "Copied",
  open_composer: "Open in composer",

  syntax_title: "Syntax Guide",
  syntax_sub: "Learn the small language that powers every track.",

  // Notifications
  notifications: "Notifications",
  notifications_empty: "No notifications yet.",
  mark_all_read: "Mark all as read",
  notif_liked: "liked",
  notif_commented: "commented on",
  notif_followed: "started following you",
} as const;

export type TextKey = keyof typeof strings;

export function useI18n() {
  const t = (key: TextKey) => strings[key];
  return { t };
}
