// All the text shown in the UI lives here so we don't hardcode strings everywhere.
// Usage: const { t } = useI18n(); then t("play") gives back "Play".
// One language only, so it's just a dictionary and a lookup.

const strings = {
  app_name: "AlgoRythm",
  brand: "Where code \nbecomes music",
  tagline:
    "Write text. Hear music. A composable, browser-based sequencer. Here music is generated by logic!",
  scroll_cue: "Scroll to compose",

  nav_composer: "Composer",
  nav_library: "Library",
  nav_syntax: "Syntax Guide",
  nav_explore: "Explore",
  nav_feed: "Feed",

  bpm: "BPM",
  play: "Play",
  stop: "Stop",
  source: "Pattern source",
  grid: "Sequencer grid",
  examples: "Example patterns",
  tracks: "tracks",
  rest_hint: "Use - for a rest.",
  mixer: "Mixer",
  mute: "Mute",
  solo: "Solo",
  master: "Master",
  visualizer: "Visualizer",
  errors: "Pattern errors",

  // Auth
  login: "Log in",
  signup: "Sign up",
  logout: "Log out",
  username: "Username",
  login_id: "Username or email",
  email: "Email",
  password: "Password",
  close: "Close",

  // Save / load compositions
  my_compositions: "My compositions",
  composition_title: "Composition title",
  save: "Save",
  load: "Load",
  delete: "Delete",
  login_to_save: "Log in to save your compositions.",
  title_required: "Please enter a title.",

  // Publish / explore / profiles
  publish: "Publish",
  unpublish: "Unpublish",
  copy_link: "Copy link",
  link_copied: "Link copied",
  by: "by",
  explore_title: "Explore",
  explore_sub: "Public compositions from the community.",
  empty_explore: "No public compositions yet — publish one to get started.",
  not_found: "This isn't available.",

  // Explore search/filter
  explore_search_placeholder: "Search compositions & people…",
  explore_search: "Search",
  explore_clear: "Clear",
  explore_filtering_by: "Filtering by tag:",
  explore_loading: "Loading compositions…",
  explore_none: "No compositions found.",
  explore_people: "People",
  explore_people_none: "No people found.",
  explore_compositions: "Compositions",

  // Wired-up UIs
  like: "Like",
  unlike: "Unlike",
  comments: "Comments",
  comment_placeholder: "Add a comment…",
  post_comment: "Post",
  login_to_comment: "Log in to comment.",
  no_comments: "No comments yet.",
  comments_error: "Couldn't load comments.",
  report: "Report",
  reported: "Reported",
  nav_admin: "Admin",
  admin_title: "Moderation",
  admin_sub: "Reported content and basic site numbers.",
  admin_forbidden: "Admins only.",
  admin_reports: "Open reports",
  admin_no_reports: "No open reports.",
  admin_remove: "Remove",
  admin_dismiss: "Dismiss",
  admin_reported_by: "reported by",
  admin_users: "Users",
  admin_compositions: "Compositions",
  admin_open_reports: "Open reports",
  settings_title: "Account settings",
  settings_sub: "Manage your password, email, and account.",
  change_password: "Change password",
  current_password: "Current password",
  new_password: "New password",
  change_email: "Change email",
  password_updated: "Password updated.",
  email_updated: "Email updated.",
  delete_account: "Delete account",
  delete_account_warn:
    "This permanently deletes your account and everything tied to it. This cannot be undone.",
  delete_account_confirm: "Yes, delete my account",
  settings_cancel: "Cancel",
  login_to_settings: "Log in to manage your account.",
  something_wrong: "Something went wrong.",
  load_more: "Load more",
  loading_more: "Loading…",
  loading: "Loading…",
  joined: "Joined",
  published_works: "Published compositions",
  no_published: "No published compositions yet.",

  // Follows + feed
  follow: "Follow",
  unfollow: "Unfollow",
  followers: "Followers",
  following: "Following",
  no_followers: "No followers yet.",
  no_following: "Not following anyone yet.",
  feed_title: "Following",
  feed_sub: "New public work from people you follow.",
  empty_feed: "Nothing here yet — follow someone to see their work.",
  login_to_feed: "Log in to see your following feed.",

  how_title: "How it works",
  how_body:
    "The Parser splits each line on ':' into a track kind and tokens. Drum tokens become Note objects bound to a percussion Instrument subclass. Melody tokens like C4 or F#5 are converted to frequencies via 440·2^((midi−69)/12). The Sequencer schedules notes ~100ms ahead on the Web Audio clock, keeping timing sample-accurate.",

  lib_title: "Instrument Library",
  lib_sub: "Every command you can write in a pattern. Click any card to copy its sample line.",
  category_drum: "Percussion",
  category_pitched: "Pitched",
  preview: "Preview sound",
  copy: "Copy",
  copied: "Copied",
  open_composer: "Open in composer",

  syntax_title: "Syntax Guide",
  syntax_sub: "Learn the small language that powers every track.",

  // Notifications
  notifications: "Notifications",
  notifications_empty: "No notifications yet.",
  mark_all_read: "Mark all as read",
  notif_liked: "liked",
  notif_commented: "commented on",
  notif_followed: "started following you",
} as const;

export type TextKey = keyof typeof strings;

export function useI18n() {
  const t = (key: TextKey) => strings[key];
  return { t };
}
